# Generated by Django 6.0.8 on 2026-08-28 14:40

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Stored in E.164 form, e.g. +989121234567.', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_iranian_mobile', message='Enter a valid Iranian mobile number in E.164 format, e.g. +989121234567.', regex='^\\+989\\d{9}$')])),
                ('is_active', models.BooleanField(default=True, help_text='Authentication gate. Clear this to block a customer without removing their history.')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, help_text='Written when a customer completes a login; never set on signup.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft-delete marker. Orders reference customers, so records are retired rather than deleted.', null=True)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ('-joined_at',),
            },
        ),
    ]
